concurrent = 10
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "${runner_name}"
  url = "https://gitlab.com/"
  token = "${runner_token}"
  executor = "docker-autoscaler"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:git"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
  [runners.autoscaler]
    plugin = "fleeting-plugin-azure"
    capacity_per_instance = 1
    max_use_count = 1
    max_instances = 10
    [runners.autoscaler.plugin_config]
      name = "${vmss_name}"
      subscription_id = "${subscription_id}"
      resource_group_name = "${rg_name}"
    [runners.autoscaler.connector_config]
      username = "packer"
      key_path = "/home/ubuntu/.ssh/id_rsa"
      timeout  = "10m"
